namespace Models.Enums
{
    public enum Manufacturer
    {
        AlfaRomeo = 1,  
        Audi = 2,
        Bentley = 3,
        Bmw = 4,
        Bugatti = 5,
        Cadillac = 6,
        Chevrolet = 7,
        Citroen = 8,
        Dacia = 9,
        Fiat = 10,
        Ford = 11,
        Jeep = 12,
        Kia = 13,
        Lada = 14,
        Lexus = 15,
        Maserati = 16,
        Maybach = 17,
        Mazda = 18,
        McLaren = 19,
        Mercedes = 20,
        Mitsubishi = 21,
        Nissan = 22,
        Opel = 23,
        Peugeot = 24,
        Renault = 25,
        Rover = 26,
        Saab = 27,
        Seat = 28,
        Smart = 29,
        Skoda = 30,
        Tesla = 11,
        Toyota = 32,
        Volkswage = 33,
        Volvo = 34,

    }
}
